version: 2 # use CircleCI 2.0
jobs:
  build: 
    working_directory: ~/circleci-demo-python-django
    docker:
      - image: continuumio/miniconda3:latest
        environment:
          MOCK_CUPY=True # Allows us to run lots of tests without a GPU
    steps:
      - checkout
      #  Uncomment the next two lines to enable caching of the conda environment 
      #  ** This will speed up tests a lot **
      #- restore_cache:
      #    key: deps-{{ .Branch }}-{{ checksum "pyks2.yml" }}
      - run: conda env create -f pyks2_test.yml
      # And these ones.
      #- save_cached:
      #    key: deps-{{ .Branch }}-{{ checksum "pyks2.yml" }}
      #    paths:
      #      - "??"
      - run: 
          name: run_tests
          command: |
              source activate pyks2_test 
              pip install -r test_requirements.txt
              pytest -m "not requires_gpu"
